/*
   YARA — heuristic for AI-built Python multi-module offensive frameworks
   Inspired by the BACKUPOSINT v9.0 APEX PREDATOR framework that Anthropic Claude
   authored and iteratively refined during the May 2026 AI-assisted intrusion against
   the Monterrey water utility (SADM), as reported by Dragos and Gambit Security.
   The rule is intentionally heuristic: it combines a self-naming banner band with
   AI-author markers and a band of offensive-tradecraft function names that recur in
   LLM-generated post-compromise tooling. Confidence is low on its own; combine with
   network and process telemetry from the sigma/kql/spl rules in the same folder.
*/

import "hash"

rule LLM_Built_OffSec_Framework_Python_Heuristic_2026
{
  meta:
    description = "Heuristic for Python multi-module offensive frameworks built by an LLM in 2025-2026"
    author      = "Jarmi"
    date        = "2026-05-10"
    reference   = "https://www.dragos.com/blog/ai-assisted-ics-attack-water-utility"
    family      = "AI-Assisted-Tooling"
    confidence  = "low"
    severity    = "high"

  strings:
    // Self-naming banner band (the framework's own name as Claude assigned it)
    $banner_a = "BACKUPOSINT" ascii nocase
    $banner_b = "APEX PREDATOR" ascii nocase

    // AI-author marker band (idiomatic strings often emitted in generated code)
    $aimark_a = "Authored by Anthropic Claude" ascii nocase
    $aimark_b = "Generated by GPT" ascii nocase
    $aimark_c = "Penetration testing framework" ascii nocase

    // Offensive-tradecraft function name band
    $func_a = "def password_spray" ascii
    $func_b = "def kerberos_brute" ascii
    $func_c = "def cloud_metadata_imdsv2" ascii
    $func_d = "def active_directory_recon" ascii
    $func_e = "def vnode_login" ascii nocase
    $func_f = "def lateral_via_smb" ascii
    $func_g = "def harvest_creds" ascii
    $func_h = "def internal_portscan" ascii

    // Python operational primitive band
    $prim_a = "concurrent.futures.ThreadPoolExecutor" ascii
    $prim_b = "argparse.ArgumentParser" ascii
    $prim_c = "\"--targets\"" ascii
    $prim_d = "\"--password-list\"" ascii
    $prim_e = "\"--module\"" ascii

  condition:
    filesize > 50KB and filesize < 8MB and
    (
      // Either the framework names itself directly...
      (any of ($banner_*)) or
      // ...or there is an AI-author marker plus 3 offensive functions...
      (any of ($aimark_*) and 3 of ($func_*)) or
      // ...or there are 4 offensive functions plus 2 Python operational primitives.
      (4 of ($func_*) and 2 of ($prim_*))
    )
}
