#!/usr/bin/env python3
"""
tools/generate_navigator.py — build MITRE ATT&CK Navigator layers from the
frontmatter of every case.

Outputs (under navigator/):
    navigator/coverage-enterprise.json   cumulative heatmap, scored by case frequency
    navigator/coverage-ics.json          cumulative ICS heatmap (only if T0xxx present)
    navigator/cases/<slug>.json          per-case layer (one technique = one case)
    navigator/README.md                  how to open in the ATT&CK Navigator

Open a layer:
    https://mitre-attack.github.io/attack-navigator/  ->  Open Existing Layer
    -> Upload from local  (or paste a raw GitHub URL of the JSON).

Run from anywhere:
    python3 tools/generate_navigator.py

Author: Jarmi
"""

from __future__ import annotations
import sys, re, json
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required", file=sys.stderr); sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
DAYS = ROOT / "days"
OUT = ROOT / "navigator"
CASES_OUT = OUT / "cases"

# Navigator / ATT&CK versions. Bump when you upgrade Navigator or the matrix.
VERSIONS = {"attack": "16", "navigator": "5.1.0", "layer": "4.5"}
GRADIENT = ["#f3f7fb", "#5a7da6", "#b03030"]  # matches repo palette: pale -> blue -> crit


def read_frontmatter(text: str):
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end < 0:
        return None
    fm = yaml.safe_load(text[4:end])
    return fm if isinstance(fm, dict) else None


def collect():
    cases = []
    for readme in sorted(DAYS.rglob("README.md")):
        fm = read_frontmatter(readme.read_text(encoding="utf-8"))
        if not fm or "date" not in fm:
            continue
        cases.append({
            "slug": readme.parent.name,
            "date": str(fm.get("date", "")),
            "title": fm.get("title", "—"),
            "clusters": fm.get("clusters") or [],
            "ent": [str(t).strip() for t in (fm.get("techniques_enterprise") or [])],
            "ics": [str(t).strip() for t in (fm.get("techniques_ics") or [])],
        })
    cases.sort(key=lambda c: c["date"])
    return cases


def base_layer(name, desc, domain):
    return {
        "name": name,
        "versions": VERSIONS,
        "domain": domain,
        "description": desc,
        "sorting": 3,  # score descending
        "showTacticRowBackground": True,
        "tacticRowBackground": "#2a4a6a",
        "selectTechniquesAcrossTactics": True,
        "hideDisabled": False,
        "techniques": [],
        "legendItems": [],
        "metadata": [],
    }


def cumulative(cases, key, domain, title):
    freq = {}
    examples = {}
    for c in cases:
        for t in c[key]:
            freq[t] = freq.get(t, 0) + 1
            examples.setdefault(t, []).append(c["date"])
    if not freq:
        return None, 0
    mx = max(freq.values())
    layer = base_layer(title, f"detection-diary cumulative coverage — {len(cases)} cases; "
                              f"score = number of cases featuring the technique.", domain)
    layer["gradient"] = {"colors": GRADIENT, "minValue": 0, "maxValue": mx}
    for t, n in sorted(freq.items(), key=lambda kv: (-kv[1], kv[0])):
        layer["techniques"].append({
            "techniqueID": t,
            "score": n,
            "comment": f"{n} case(s); first {min(examples[t])}, last {max(examples[t])}",
            "enabled": True,
        })
    return layer, mx


def per_case(c, key, domain):
    if not c[key]:
        return None
    layer = base_layer(f"{c['date']} — {c['slug']}",
                       f"{c['title']} — clusters: {', '.join(c['clusters']) or 'n/a'}", domain)
    layer["gradient"] = {"colors": ["#5a7da6", "#5a7da6"], "minValue": 0, "maxValue": 1}
    for t in c[key]:
        layer["techniques"].append({
            "techniqueID": t, "score": 1, "enabled": True,
            "color": "#5a7da6", "comment": c["title"][:80],
        })
    return layer


README = """# ATT&CK Navigator layers — detection-diary

Auto-generated by `tools/generate_navigator.py`. **Do not edit by hand.**

## Files

| File | What it shows |
|---|---|
| `coverage-enterprise.json` | Cumulative Enterprise ATT&CK heatmap — every technique seen across all cases, scored by how many cases feature it. The hot cells are the diary's most-covered techniques. |
| `coverage-ics.json` | Same, for ICS ATT&CK (`T0xxx`) — present only if the diary has ICS cases. |
| `cases/<slug>.json` | One layer per case — just that case's techniques highlighted. |

## How to open

1. Go to the **[ATT&CK Navigator](https://mitre-attack.github.io/attack-navigator/)**.
2. **Open Existing Layer -> Upload from local**, pick a JSON file.
   (Or host the repo on GitHub Pages and paste the raw JSON URL.)
3. The cumulative layer uses a pale -> blue -> red gradient: redder = covered by
   more cases.

Score on the cumulative layer = number of cases featuring that technique, so the
heatmap doubles as a coverage-gap map: cold/empty cells are techniques the diary
has not yet taught.
"""


def main():
    cases = collect()
    if not cases:
        print("no cases found"); return 1
    OUT.mkdir(parents=True, exist_ok=True)
    CASES_OUT.mkdir(parents=True, exist_ok=True)

    ent_layer, ent_mx = cumulative(cases, "ent", "enterprise-attack",
                                   "detection-diary — Enterprise coverage")
    if ent_layer:
        (OUT / "coverage-enterprise.json").write_text(
            json.dumps(ent_layer, indent=2, ensure_ascii=False), encoding="utf-8")

    ics_layer, ics_mx = cumulative(cases, "ics", "ics-attack",
                                   "detection-diary — ICS coverage")
    if ics_layer:
        (OUT / "coverage-ics.json").write_text(
            json.dumps(ics_layer, indent=2, ensure_ascii=False), encoding="utf-8")

    n_case_layers = 0
    for c in cases:
        layer = per_case(c, "ent", "enterprise-attack")
        if layer:
            (CASES_OUT / f"{c['slug']}.json").write_text(
                json.dumps(layer, indent=2, ensure_ascii=False), encoding="utf-8")
            n_case_layers += 1

    (OUT / "README.md").write_text(README, encoding="utf-8")

    uniq_ent = len({t for c in cases for t in c["ent"]})
    uniq_ics = len({t for c in cases for t in c["ics"]})
    print(f"Navigator layers built from {len(cases)} cases.")
    print(f"  Enterprise: {uniq_ent} unique techniques, hottest cell = {ent_mx} cases")
    if ics_layer:
        print(f"  ICS       : {uniq_ics} unique techniques, hottest cell = {ics_mx} cases")
    print(f"  Per-case  : {n_case_layers} layers in navigator/cases/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
