#!/usr/bin/env python3
"""
tools/generate_index.py — regenerate INDEX.md and the auto-views
(byActor/, byTechnique/, byPlatform/) from the YAML frontmatter
of every day's README.md.

Storage layout (v2, sharded by year/month):

    days/YYYY/MM/YYYY-MM-DD_<slug>/README.md

The collector recurses, so any nesting under days/ works; the physical path
is cosmetic — every link is computed from the file location, and the
chronology is driven by the `date:` field in the frontmatter, not the path.

Outputs:
  - INDEX.md                          (gallery + chronological by month)
  - README.md gallery block           (between AUTOGEN:GALLERY markers)
  - byActor/<slug>/README.md
  - byTechnique/<TID>/README.md
  - byPlatform/<platform>/README.md

Run from anywhere:
    python3 tools/generate_index.py
"""

from __future__ import annotations
import os, sys, re, shutil
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required (pip install pyyaml or apt install python3-yaml)", file=sys.stderr)
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
DAYS_DIR = ROOT / "days"

# Set this to your published Pages URL once Pages is enabled (source: /docs).
PAGES_URL = "./docs/index.html"

GENERATED_HEADER = (
    "<!-- AUTO-GENERATED by tools/generate_index.py — DO NOT EDIT BY HAND. -->\n"
    "<!-- Source of truth: YAML frontmatter in each day's README.md -->\n\n"
)

def slugify(s: str) -> str:
    s = s.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "unknown"

def read_frontmatter(md_path: Path):
    text = md_path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end < 0:
        return None
    fm = yaml.safe_load(text[4:end])
    return fm if isinstance(fm, dict) else None

def collect_days():
    """Recurse under days/ and load every day folder's README.md frontmatter.

    Works for both the legacy flat layout (days/<slug>/) and the sharded
    layout (days/YYYY/MM/<slug>/).
    """
    days = []
    if not DAYS_DIR.is_dir():
        return days
    for readme in sorted(DAYS_DIR.rglob("README.md")):
        fm = read_frontmatter(readme)
        if fm is None or "date" not in fm:
            continue
        folder = readme.parent
        fm["date"] = str(fm.get("date", ""))   # YAML may parse date: into a date object
        fm["_slug"] = folder.name
        fm["_path"] = folder.relative_to(ROOT).as_posix()
        days.append(fm)
    return days

def _counters(days):
    clusters, techs, plats, sectors = set(), set(), set(), set()
    for d in days:
        clusters |= set(d.get("clusters") or [])
        techs |= set((d.get("techniques_enterprise") or []) + (d.get("techniques_ics") or []))
        plats |= set(d.get("platforms") or [])
        sectors |= set(d.get("sectors") or [])
    dates = sorted(d.get("date", "") for d in days if d.get("date"))
    span = f"{dates[0]} -> {dates[-1]}" if dates else "—"
    return {
        "cases": len(days), "clusters": len(clusters), "techniques": len(techs),
        "platforms": len(plats), "sectors": len(sectors), "span": span,
    }

def _thumb_card(d):
    clusters = " · ".join(d.get("clusters") or [])
    return (
        f'<td align="center" valign="top" width="33%">'
        f'<a href="{d["_path"]}/"><img src="{d["_path"]}/kill_chain.svg" alt="{d.get("date","")} kill chain" width="240"></a><br>'
        f'<sub><b>{d.get("date","?")}</b><br>{clusters}</sub>'
        f'</td>'
    )

def render_index(days):
    c = _counters(days)
    out = [GENERATED_HEADER, "# INDEX\n",
        f"**{c['cases']} cases** · **{c['clusters']} actors/clusters** · "
        f"**{c['techniques']} ATT&CK techniques** · **{c['platforms']} platforms** · "
        f"**{c['sectors']} sectors** · {c['span']}\n",
        f"> Visual gallery (filterable, light/dark): **[open the Pages site]({PAGES_URL})**. "
        "Browse facets: [by actor](byActor/) · [by technique](byTechnique/) · [by platform](byPlatform/).\n",
        "\n<!-- Auto-generated. Edit per-day frontmatter to change anything here. -->\n",
        "---\n",
    ]
    ordered = sorted(days, key=lambda x: x.get("date", ""), reverse=True)

    out += ["## Recent\n", "<table>"]
    recent = ordered[:12]
    for i in range(0, len(recent), 3):
        out.append("<tr>")
        for d in recent[i:i+3]:
            out.append(_thumb_card(d))
        out.append("</tr>")
    out += ["</table>\n", "---\n", "## All cases by month\n"]

    by_month = {}
    for d in ordered:
        ym = (d.get("date", "0000-00"))[:7]
        by_month.setdefault(ym, []).append(d)
    for ym in sorted(by_month, reverse=True):
        rows = by_month[ym]
        out.append(f"<details><summary><b>{ym}</b> — {len(rows)} case(s)</summary>\n")
        out.append("| Date | Case | Clusters | Platforms |")
        out.append("|---|---|---|---|")
        for d in rows:
            clusters = " · ".join(d.get("clusters") or [])
            plats = ", ".join(d.get("platforms") or [])
            title = (d.get("title") or "—")
            out.append(f"| {d.get('date','?')} | [{title}]({d['_path']}/) | {clusters} | {plats} |")
        out.append("\n</details>\n")

    return "\n".join(out).rstrip() + "\n"

README_START = "<!-- AUTOGEN:GALLERY:START -->"
README_END = "<!-- AUTOGEN:GALLERY:END -->"

def render_readme_block(days):
    c = _counters(days)
    ordered = sorted(days, key=lambda x: x.get("date", ""), reverse=True)
    lines = [README_START,
        f"**{c['cases']} cases** · **{c['clusters']} actors/clusters** · "
        f"**{c['techniques']} ATT&CK techniques** · **{c['platforms']} platforms** · "
        f"**{c['sectors']} sectors** · {c['span']}",
        "",
        f"> Visual gallery (filterable, light/dark): **[open the Pages site]({PAGES_URL})** · "
        "full list in **[INDEX.md](INDEX.md)** · facets: "
        "[actor](byActor/) · [technique](byTechnique/) · [platform](byPlatform/)",
        "",
        "<table>"]
    recent = ordered[:6]
    for i in range(0, len(recent), 3):
        lines.append("<tr>")
        for d in recent[i:i+3]:
            lines.append(_thumb_card(d))
        lines.append("</tr>")
    lines += ["</table>", README_END]
    return "\n".join(lines)

def patch_readme(days):
    readme = ROOT / "README.md"
    if not readme.is_file():
        return
    text = readme.read_text(encoding="utf-8")
    block = render_readme_block(days)
    if README_START in text and README_END in text:
        new = re.sub(re.escape(README_START) + r".*?" + re.escape(README_END),
                     lambda m: block, text, count=1, flags=re.S)
    else:
        m = re.search(r"^# .+$", text, re.M)
        if m:
            idx = m.end()
            new = text[:idx] + "\n\n" + block + "\n" + text[idx:]
        else:
            new = block + "\n\n" + text
    readme.write_text(new, encoding="utf-8")
    print("  patched README.md gallery block")

def regenerate_view(view_dir: Path, group_dict: dict, view_label: str):
    wipe_failed = False
    if view_dir.exists():
        try:
            shutil.rmtree(view_dir)
        except (PermissionError, OSError) as e:
            print(f"  [warn] cannot wipe {view_dir.name}/ ({e.__class__.__name__}); merging instead.")
            wipe_failed = True

    view_dir.mkdir(parents=True, exist_ok=True)

    top = [GENERATED_HEADER,
           f"# {view_label}\n",
           "Auto-generated view. Each subfolder lists the days that match.\n",
           "Source of truth: each day's `README.md` frontmatter.\n\n",
           "| Group | Days |",
           "|---|---|"]

    expected_slugs = set()
    for key in sorted(group_dict):
        slug = slugify(key)
        expected_slugs.add(slug)
        sub = view_dir / slug
        sub.mkdir(parents=True, exist_ok=True)

        days_for_key = sorted(group_dict[key], key=lambda x: x.get("date",""), reverse=True)
        body = [GENERATED_HEADER,
                f"# {view_label}: {key}\n",
                f"{len(days_for_key)} day(s) covering this {view_label.lower().rstrip('s')}.\n\n"]
        body.append("| Date | Title | Clusters | Path |")
        body.append("|---|---|---|---|")
        for d in days_for_key:
            clusters = " · ".join(d.get("clusters") or [])
            rel = "../../" + d["_path"]
            body.append(f"| {d.get('date','?')} | {d.get('title','—')} | {clusters} | [`{d['_slug']}/`]({rel}/) |")
        (sub / "README.md").write_text("\n".join(body) + "\n", encoding="utf-8")
        top.append(f"| [{key}](./{slug}/) | {len(days_for_key)} |")

    (view_dir / "README.md").write_text("\n".join(top) + "\n", encoding="utf-8")

    if wipe_failed:
        actual_slugs = {p.name for p in view_dir.iterdir() if p.is_dir()}
        stale = sorted(actual_slugs - expected_slugs)
        if stale:
            print(f"  [warn] stale entries in {view_dir.name}/ — run "
                  f"`git rm -r {' '.join(view_dir.name + '/' + s for s in stale)}` before commit:")
            for s in stale:
                print(f"           {view_dir.name}/{s}")


def main():
    days = collect_days()
    if not days:
        print("no days with frontmatter found"); return 1
    print(f"Loaded {len(days)} day(s) from {DAYS_DIR.relative_to(ROOT)}/")

    (ROOT / "INDEX.md").write_text(render_index(days), encoding="utf-8")
    print("  wrote INDEX.md")

    patch_readme(days)

    by_cluster = {}
    for d in days:
        for c in d.get("clusters") or []:
            by_cluster.setdefault(c, []).append(d)
    regenerate_view(ROOT / "byActor", by_cluster, "Actors")
    print(f"  wrote byActor/  ({len(by_cluster)} cluster(s))")

    by_tech = {}
    for d in days:
        for t in (d.get("techniques_enterprise") or []) + (d.get("techniques_ics") or []):
            by_tech.setdefault(t, []).append(d)
    regenerate_view(ROOT / "byTechnique", by_tech, "Techniques")
    print(f"  wrote byTechnique/  ({len(by_tech)} technique(s))")

    by_plat = {}
    for d in days:
        for p in d.get("platforms") or []:
            by_plat.setdefault(p, []).append(d)
    regenerate_view(ROOT / "byPlatform", by_plat, "Platforms")
    print(f"  wrote byPlatform/  ({len(by_plat)} platform(s))")

    return 0

if __name__ == "__main__":
    sys.exit(main())
