#!/usr/bin/env python3
# Author: Jarmi
# Date:   2026-05-08
# Purpose: Generate one self-contained ADX-runnable .kql file per detection
#          rule under days/*/kql/, with the literal rule body and a count
#          assertion at the end. Output goes to tools/adx_rules/<slug>.kql.
#          The user pastes ONE file at a time in the ADX query window and runs.
#          Each output file is ready to execute against the bootstrap+seed
#          tables. Hits > 0 means the rule fired against the seed.
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RULES = sorted(Path(ROOT, "days").glob("*/kql/*.kql"))
OUT_DIR = ROOT / "tools" / "adx_rules"


def slug(p: Path) -> str:
    day = p.parts[-3].split("_", 1)[0]
    return f"r_{day.replace('-', '_')}__{p.stem}"


def strip_header(text: str) -> str:
    out, in_header = [], True
    for line in text.splitlines():
        if in_header and (line.startswith("//") or not line.strip()):
            continue
        in_header = False
        out.append(line)
    return "\n".join(out).rstrip()


def trim_final_pipeline(body: str) -> str:
    # Walk from the end, drop the trailing '| sort/order/project/top ...' step
    # together with any continuation lines (lines that do not start with '|').
    lines = body.splitlines()
    # Find index of the LAST step pipe.
    last_pipe_idx = None
    for i, ln in enumerate(lines):
        if ln.lstrip().startswith("|"):
            last_pipe_idx = i
    if last_pipe_idx is None:
        return body
    last_step = lines[last_pipe_idx].lstrip()
    drop_step = last_step.startswith(("| sort", "| order", "| project", "| top",
                                       "| extend rule", "| summarize hits"))
    if not drop_step:
        return body
    # Drop the step line and any continuation lines below it.
    return "\n".join(lines[:last_pipe_idx]).rstrip()


def emit_rule_file(p: Path) -> str:
    raw = p.read_text(encoding="utf-8", errors="replace")
    body = strip_header(raw)
    body = trim_final_pipeline(body)
    body = body + "\n| summarize hits = count()"
    rel = p.relative_to(ROOT).as_posix()
    s = slug(p)
    out = (
        f"// =============================================================================\n"
        f"// {s}\n"
        f"// Source: {rel}\n"
        f"// Generated by tools/generate_adx_tests_full.py — do not edit.\n"
        f"// Paste this whole file into the ADX query window and Run. The trailing\n"
        f"// '| summarize hits = count()' returns the number of rows the rule fired on.\n"
        f"// Expected: hits > 0 against the seed in tools/adx_seed.kql.\n"
        f"// =============================================================================\n\n"
        f"{body}\n"
    )
    return out


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    # Wipe stale files so removed rules don't linger.
    for old in OUT_DIR.glob("*.kql"):
        old.unlink()
    manifest_lines = [
        "# tools/adx_rules — one ADX-runnable file per detection rule",
        "",
        "Each file under this directory is the literal body of a `days/*/kql/*.kql`",
        "rule with its trailing `| sort` / `| project` / `| top` step removed and a",
        "`| summarize hits = count()` appended. Paste any single file in the ADX",
        "query window after running `adx_bootstrap.kql` and `adx_seed.kql`, and",
        "click Run. Hits > 0 means the rule fired against the seed.",
        "",
        "| Rule slug | Source file |",
        "|---|---|",
    ]
    for p in RULES:
        s = slug(p)
        out_path = OUT_DIR / f"{s}.kql"
        out_path.write_text(emit_rule_file(p), encoding="utf-8")
        manifest_lines.append(f"| `{s}` | `{p.relative_to(ROOT).as_posix()}` |")
    (OUT_DIR / "README.md").write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")
    print(f"wrote {len(RULES)} rule files to {OUT_DIR.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
