#!/usr/bin/env python3
"""
tools/generate_index.py — regenerate INDEX.md and the auto-views
(byActor/, byTechnique/, byPlatform/) from the YAML frontmatter
of every days/<slug>/README.md.

Source of truth: each day's README.md frontmatter must include:

    ---
    date: YYYY-MM-DD
    title: "..."
    clusters: [...]                # list of strings
    cluster_country: "..."
    techniques_enterprise: [...]   # MITRE ATT&CK Enterprise IDs
    techniques_ics: [...]          # MITRE ATT&CK ICS IDs (T08xx, T0xxxx)
    platforms: [...]               # short tags: windows, linux, ot-ics, ...
    sectors: [...]                 # short tags
    ---

Outputs:
  - INDEX.md                                     (chronological + by-* tables)
  - byActor/<slug>/README.md                     (one file per cluster alias)
  - byTechnique/<TID>/README.md                  (one per ATT&CK technique)
  - byPlatform/<platform>/README.md              (one per platform tag)

Run from anywhere:
    python3 tools/generate_index.py
"""

from __future__ import annotations
import os, sys, re, shutil
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required (pip install pyyaml or apt install python3-yaml)", file=sys.stderr)
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
DAYS_DIR = ROOT / "days"

GENERATED_HEADER = (
    "<!-- AUTO-GENERATED by tools/generate_index.py — DO NOT EDIT BY HAND. -->\n"
    "<!-- Source of truth: YAML frontmatter in each days/<slug>/README.md -->\n\n"
)

def slugify(s: str) -> str:
    s = s.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "unknown"

def read_frontmatter(md_path: Path):
    text = md_path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end < 0:
        return None
    fm = yaml.safe_load(text[4:end])
    return fm if isinstance(fm, dict) else None

def collect_days():
    days = []
    for child in sorted(DAYS_DIR.iterdir()):
        if not child.is_dir(): continue
        readme = child / "README.md"
        if not readme.is_file(): continue
        fm = read_frontmatter(readme)
        if fm is None: continue
        fm["_slug"] = child.name
        fm["_path"] = child.relative_to(ROOT).as_posix()
        days.append(fm)
    return days

def render_index(days):
    out = [GENERATED_HEADER, "# INDEX\n",
           "Three views of every entry in this notebook: chronological, by actor/cluster, and by MITRE ATT&CK technique.\n",
           "Auto-generated. Edit the per-day frontmatter to change anything here.\n",
           "\n---\n",
           "## Chronological (newest first)\n",
           "| Date | Slug | Headline | Clusters | Sectors |",
           "|---|---|---|---|---|",
    ]
    for d in sorted(days, key=lambda x: x.get("date",""), reverse=True):
        clusters = " · ".join(d.get("clusters") or [])
        sectors  = ", ".join(d.get("sectors")  or [])
        out.append(f"| {d.get('date','?')} | [`{d['_slug']}`]({d['_path']}/) | {d.get('title','—')} | {clusters} | {sectors} |")

    # By actor/cluster
    out += ["", "---", "", "## By actor / cluster", ""]
    by_cluster = {}
    for d in days:
        for c in d.get("clusters") or []:
            by_cluster.setdefault(c, []).append(d)
    for cluster in sorted(by_cluster):
        out.append(f"### {cluster}")
        for d in sorted(by_cluster[cluster], key=lambda x: x.get("date",""), reverse=True):
            out.append(f"- {d.get('date','?')} — [{d.get('title','—')}]({d['_path']}/) · *{d.get('cluster_country','')}*")
        out.append("")

    # By MITRE technique
    out += ["---", "", "## By MITRE ATT&CK technique (Enterprise + ICS)", ""]
    by_tech = {}
    for d in days:
        for t in (d.get("techniques_enterprise") or []) + (d.get("techniques_ics") or []):
            by_tech.setdefault(t, []).append(d)
    out += ["| Technique | Cases |", "|---|---|"]
    for t in sorted(by_tech):
        cases = ", ".join(f"[`{x['_slug']}`]({x['_path']}/)" for x in sorted(by_tech[t], key=lambda x: x.get("date","")))
        out.append(f"| {t} | {cases} |")

    # By platform
    out += ["", "---", "", "## By platform", ""]
    by_plat = {}
    for d in days:
        for p in d.get("platforms") or []:
            by_plat.setdefault(p, []).append(d)
    for plat in sorted(by_plat):
        out.append(f"### {plat}")
        for d in sorted(by_plat[plat], key=lambda x: x.get("date",""), reverse=True):
            out.append(f"- {d.get('date','?')} — [{d.get('title','—')}]({d['_path']}/)")
        out.append("")

    return "\n".join(out).rstrip() + "\n"

def regenerate_view(view_dir: Path, group_dict: dict, view_label: str):
    """Rebuild a view directory: byActor/, byTechnique/, byPlatform/.

    On filesystems that allow unlink (Linux, macOS, native Windows NTFS), we
    wipe the directory cleanly so stale entries do not linger.

    On mounts that disallow file/dir deletion (some WSL / Cowork bind-mounts),
    we fall back to MERGE mode: overwrite existing files in-place and print a
    warning listing entries that look stale (subfolders present on disk but
    absent from the current frontmatter).
    """
    wipe_failed = False
    if view_dir.exists():
        try:
            shutil.rmtree(view_dir)
        except (PermissionError, OSError) as e:
            print(f"  [warn] cannot wipe {view_dir.name}/ ({e.__class__.__name__}); "
                  "merging instead.")
            wipe_failed = True

    view_dir.mkdir(parents=True, exist_ok=True)

    # Top-level README listing all groups
    top = [GENERATED_HEADER,
           f"# {view_label}\n",
           "Auto-generated view. Each subfolder lists the days that match.\n",
           "Source of truth: `days/<slug>/README.md` frontmatter.\n\n",
           "| Group | Days |",
           "|---|---|"]

    expected_slugs = set()
    for key in sorted(group_dict):
        slug = slugify(key)
        expected_slugs.add(slug)
        sub = view_dir / slug
        sub.mkdir(parents=True, exist_ok=True)

        days_for_key = sorted(group_dict[key], key=lambda x: x.get("date",""), reverse=True)
        body = [GENERATED_HEADER,
                f"# {view_label}: {key}\n",
                f"{len(days_for_key)} day(s) covering this {view_label.lower().rstrip('s')}.\n\n"]
        body.append("| Date | Title | Clusters | Path |")
        body.append("|---|---|---|---|")
        for d in days_for_key:
            clusters = " · ".join(d.get("clusters") or [])
            rel = "../../" + d["_path"]
            body.append(f"| {d.get('date','?')} | {d.get('title','—')} | {clusters} | [`{d['_slug']}/`]({rel}/) |")
        (sub / "README.md").write_text("\n".join(body) + "\n", encoding="utf-8")
        top.append(f"| [{key}](./{slug}/) | {len(days_for_key)} |")

    (view_dir / "README.md").write_text("\n".join(top) + "\n", encoding="utf-8")

    # If wipe failed, list stale subfolders so the user can git-rm them
    if wipe_failed:
        actual_slugs = {p.name for p in view_dir.iterdir() if p.is_dir()}
        stale = sorted(actual_slugs - expected_slugs)
        if stale:
            print(f"  [warn] stale entries in {view_dir.name}/ — run "
                  f"`git rm -r {' '.join(view_dir.name + '/' + s for s in stale)}` "
                  "before commit:")
            for s in stale:
                print(f"           {view_dir.name}/{s}")


def main():
    days = collect_days()
    if not days:
        print("no days with frontmatter found"); return 1
    print(f"Loaded {len(days)} day(s) from {DAYS_DIR.relative_to(ROOT)}/")

    # 1) INDEX.md
    (ROOT / "INDEX.md").write_text(render_index(days), encoding="utf-8")
    print("  wrote INDEX.md")

    # 2) byActor/
    by_cluster = {}
    for d in days:
        for c in d.get("clusters") or []:
            by_cluster.setdefault(c, []).append(d)
    regenerate_view(ROOT / "byActor", by_cluster, "Actors")
    print(f"  wrote byActor/  ({len(by_cluster)} cluster(s))")

    # 3) byTechnique/
    by_tech = {}
    for d in days:
        for t in (d.get("techniques_enterprise") or []) + (d.get("techniques_ics") or []):
            by_tech.setdefault(t, []).append(d)
    regenerate_view(ROOT / "byTechnique", by_tech, "Techniques")
    print(f"  wrote byTechnique/  ({len(by_tech)} technique(s))")

    # 4) byPlatform/
    by_plat = {}
    for d in days:
        for p in d.get("platforms") or []:
            by_plat.setdefault(p, []).append(d)
    regenerate_view(ROOT / "byPlatform", by_plat, "Platforms")
    print(f"  wrote byPlatform/  ({len(by_plat)} platform(s))")

    return 0

if __name__ == "__main__":
    sys.exit(main())
